### ISSUE TITLE
Cannot use non-Oak signs

### ISSUE THREAD

**Issue by Brickgard** [qKing12/AuctionMasterItemDisplay#1]
Only Oak signs get activated/used by the plugin; all other signs are untouched/unused.
Would be nice for ```BIRCH_SIGN
SPRUCE_SIGN
JUNGLE_SIGN
ACACIA_SIGN
DARK_OAK_SIGN
CRIMSON_SIGN
WARPED_SIGN``` to also be supported.

**Comment by qKing12** [comment]
I understand what you are saying, at the moment is just more convenient for me to use oak only, since that's the material compatible with both older version and newer ones. WIll consider it for future updates
